### ISSUE TITLE
indentation is inconsistent

### ISSUE THREAD

**Issue by zeffii** [zeffii/sods-blender-plugins#2]
due to inconsistent indentation it isn't easy to fix this automatically, but I made a start anyway.

**Comment by zeffii** [comment]
other bugs can be fixed first

**Comment by hizeffi** [comment]
Here are the files you requested
http://spinout182.com/mqd/object_link_boy.zobj
http://spinout182.com/mqd/link_animetion.zdata
http://spinout182.com/mqd/gameplay_keep.zobj
rename link_animetion to segment_07.zdata and gameplay_keep.zobj to segment_04.zdata and keep the other filename the same
I have no idea what the problem is and I really appreciate all of your help. thank you 
my question:http://blender.stackexchange.com/questions/33717/typeerror-list-does-not-support-the-buffer-interface

**Comment by hizeffi** [comment]
make sure the files are in the same folder

**Comment by zeffii** [comment]
no guarantee I can fix this, but blender.stackexchange isn't the place for discussing broken addons :)

note to self:
```
rename 
link_animetion.zdata     ->  segment_07.zdata
gameplay_keep.zobj     ->  segment_04.zdata
object_link_boy.zobj      ->  object_link_boy.zobj
```

is that right?
